### ISSUE TITLE
Update Rating

### ISSUE THREAD

**Issue by chizzycrusty** [willvincent/laravel-rateable#14]
Hi,

Your package is nice but I'm struggling to find a way to update a rating. My user can only rate a post once, then update his rating if he wants to.
Any idea of how I can do this ?

**Comment by willvincent** [comment]
Rating has a model, which makes working with it not too terrible.

So if you wanted to allow the current use to update their _existing_ rating of a thing (lets say post for the sake of clarity), you'd first need to check if they already _have_ a rating:

```
$post = App\Post::find(1);

$rating = willvincent\Rateable\Rating::findOrNew([
  'user_id' => Auth::id(),
  'rateable_type' => App\Post::class,
  'rateable_id' => $post->id,
]);

// If this is a new rating we need to specify the user id:
if (!$rating->id) {
  $rating->user_id = Auth::id();
}

// Whether new or not, set the proper rating value, then save it through the post:
$rating->rating = $newRatingValue;
$post->ratings()->save($rating);
```

**Comment by chizzycrusty** [comment]
I tried your solution and got this error:

> FatalThrowableError in MorphOneOrMany.php line 148:
Type error: Argument 1 passed to Illuminate\Database\Eloquent\Relations\MorphOneOrMany::save() must be an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate\Database\Eloquent\Collection given, called in /Applications/MAMP/htdocs/Kosmic/blog/app/Http/Controllers/PostController.php on line 179

I also tried several other things, and if I go for:
`$post->ratings()->update(['rating' => $newRating]);`
instead of:
`$rating->rating = $newRatingValue;
$post->ratings()->save($rating);`

I manage to update all of the ratings of the post but I can't find a way to only update the rating of the user.

FYI I found out that Ghanem's package: https://github.com/AbdullahGhanem/rating has a way to do an update, I tried to implement his function to your Rateable.php but I am not good enough and I can't get it right. If that can help you find a solution.

**Comment by willvincent** [comment]
Sorry that should've been `firstOrNew()` not `findOrNew()`

**Comment by chizzycrusty** [comment]
Problem is solved, here is how:
```
    /**
     * Update Rating Post
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function updateRating(Request $request, Post $post)
    {
        $newRating = $request->input('rating-post');

        $rating = Rating::where([
            ['user_id', Auth::id()],
            ['rateable_id', $post->id]
        ])->first();

        $rating->rating = $newRating;

        $post->ratings()->save($rating);

        return redirect('home');
    }
```

**Comment by iVanilla** [comment]
@willvincent How to delete a rating?

**Comment by willvincent** [comment]
@iVanilla Rating is a model... you can delete ratings the same way you'd delete any other model in your code. Find the rating you want to delete, and delete it.
https://laravel.com/docs/5.4/eloquent#deleting-models

**Comment by iVanilla** [comment]
@willvincent Thanks.

**Comment by willvincent** [comment]
Yes, and ratings are represented by a rating model. So you can delete it as you would any other model.

**Comment by bleuscyther** [comment]
Just in case you have many rateable models: 
```php 
  /**
     * Update Rating Post
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function updateRating(Request $request, Post $post)
    {
        $newRating = $request->input('rating-post');

        $rating = Rating::where([
            ['user_id', Auth::id()],
            ['rateable_id', $post->id],
            ['rateable_type', 'App\Post']
        ])->first();

        $rating->rating = $newRating;

        $post->ratings()->save($rating);

        return redirect('home');
    }
```

**Comment by Gaguchi** [comment]
Do i need to add this function to the Rateable.php or the controller (or somewhere else)?

**Comment by bleuscyther** [comment]
In the controller its to filter out base on the model.

**Comment by Gaguchi** [comment]
I did add it to the controller but it still doesn't work.

for reference, I was following along [this tutorial](https://hdtuto.com/article/php-laravel-5-rating-system-example-from-scratch) and I got stuck here.
