### ISSUE TITLE
n+1 Problem

### ISSUE THREAD

**Issue by pwnz22** [willvincent/laravel-rateable#17]
Firstly i want to thank you for this good package ;)

I have n+1 problem when i'm loading the ratings.

I have `companies` which has `comments` with `morphMany relationship`.

**Company.php**
```
    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }
```
When a `User` writing a comment he can rate the `Company`:
```
       $company->comments()->create([
            'body' => $request->body,
            'user_id' => $user->id
        ]);

        $rating = new Rating;
        $rating->rating = $request->rating;
        $rating->user_id = $user->id;

        $company->ratings()->save($rating);
```
So when i loop all comments in company.blade.php and also want to show the rating i do this:
```
@foreach($comments as $comment)
    {{ $comment->user_rating($company->id)->rating }}
@endforeach

```
user_rating method:
 ```
  public function user_rating($company_id)
    {
        return Rating::where('user_id', $this->user->id)->where('rateable_id', $company_id)->first();
    }
```
And here is coming the n+1 problem) Any suggestions how to fix this?

**Comment by pwnz22** [comment]
I ended up with adding `rating_id  `to `comments `table and using `->belongsTo()` relationship.

**Comment by EricBusch** [comment]
I had the same n+1 issue trying to eager load the relationships. Here's how I did eager loading.

**Model**

```php
$flashcards = Flashcard::query()->with(['ratings'])->orderBy('updated_at', 'desc')->get();
```

**View**

```php
@foreach($flashcards as $flashcard)
    {{ $flashcard->ratings->avg('rating') }}
    {{ $flashcard->ratings->sum('rating') }}
@endforeach
```

Hope this helps!
