### ISSUE TITLE
show rating option in blade

### ISSUE THREAD

**Issue by robertnicjoo** [willvincent/laravel-rateable#20]
Hi,
I just installed this project on L5.5, I don't know how exactly i can show this option in my posts blade template?

I want users be able to rate between 1 to 5 star for each post.

Thanks.

**Comment by robertnicjoo** [comment]
anyone here to help?

**Comment by willvincent** [comment]
The package does not provide any front end. You would probably most easily be able to accomplish it with something like Vue, and exposing api endpoints to post to via ajax. This package merely provides the relationship and a few methods to fetch values.

**Comment by robertnicjoo** [comment]
@willvincent so what you say is simply there is no use for this package right? cause if i cant get rating for posts from users what this package is good for?!

and other issue is if i save codes provided in docs in my model i will get errors.

**Comment by willvincent** [comment]
No, there's definitely a use, but it doesn't provide UI. This package provides _several_ ways to do ratings, but UI implementation is not included -- because everyone will have their own specific needs. It's a piece of the solution, not the entire implementation from start to finish.
