### ISSUE TITLE
how to get user info

### ISSUE THREAD

**Issue by robertnicjoo** [willvincent/laravel-rateable#21]
Hi,

I'm not able to get user info in my blade, here I explained it all:

https://stackoverflow.com/questions/46921645/getting-user-info-in-rates-in-laravel

**Comment by robertnicjoo** [comment]
hello, i don't know why this is closed! but anyone can help me to get user info on each ratings?
still need to solve this.

**Comment by fetrarij** [comment]
#19 this fix should solve your issue. Upgrade to use the latest version.

**Comment by robertnicjoo** [comment]
@fetrarij i believe my package is update, that commit is 5 months old, i installed this package 2months ago.

should i change anything manually?

**Comment by fetrarij** [comment]
@robertnicjoo wich version do you have in your composer.json ? check  vendor/willvincent/laravel-reateable/src/Rateable/Rating.php and see how this model load your user model.

**Comment by robertnicjoo** [comment]
@fetrarij `"willvincent/laravel-rateable": "~1.0"`  


```php
<?php namespace willvincent\Rateable;

use Config;
use Illuminate\Database\Eloquent\Model;

class Rating extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $fillable = ['rating'];

    /**
     * @return mixed
     */
    public function rateable()
    {
        return $this->morphTo();
    }

    /**
     * Rating belongs to a user.
     *
     * @return User
     */
    public function user()
    {
        return $this->belongsTo(Config::get('auth.model'));
    }
}
```

**Comment by fetrarij** [comment]
@robertnicjoo  You still use the version before PR #19 , I suggest to update to use the master version.

```
"require": { "willvincent/laravel-rateable" : "dev-master" }
"minimum-stability": "dev"
```

Another alternative is to copy Rateable.php and Rate.php from master into your models folder and use your own namespace (App\Model\Rating && App\Model\Rateable ) instead of the plugin namespace.

**Comment by robertnicjoo** [comment]
@fetrarij  I've made changes in rating.php but the first part i got lost in it,


```
"require": { "willvincent/laravel-rateable" : "dev-master" }
"minimum-stability": "dev"
```

where should i add these?

**Comment by willvincent** [comment]
Hey guys, sorry I never did a new release after that PR.. just did one. You shouldn't have to update your composer file at all anymore (that's where the changes you asked about would've gone, @robertnicjoo )

Just run `composer update willvincent/laravel-rateable` and you should be all set.

**Comment by robertnicjoo** [comment]
@willvincent thanks man, just for future knowledge now that commit is in master or  no? i mean next time i install this package everything is set or should i again update etc. ?

**Comment by fetrarij** [comment]
@robertnicjoo everything is good in future because he have just did a new release

**Comment by robertnicjoo** [comment]
perfect, appreciate it. I'll close it now.

thank you all.
