### ISSUE TITLE
Scope doesn't work with this package

### ISSUE THREAD

**Issue by robertnicjoo** [willvincent/laravel-rateable#22]
I try to get rating with status_id column (added by me) but i get error of:

```
Call to undefined method Illuminate\Database\Query\Builder::Status()
```

my scope:

```php
public function scopeStatus($query, $status)
    {
        $statuses = Status::where('title', $status)->pluck('id');
        return $query->whereIn('status_id', $statuses);
    }
```

my controller

```php
$rates = $product->ratings()->orderby('id', 'desc')->Status('Active')->get();
```

error comes from my controller code, i searched a lot and all samples where like:

```php
$user = Userr::Status('Active')->get();
```

in my case i cannot use `::` and I have to use `ratings()` not sure if it's relative, just the only thing I could think of!

any idea?

**Comment by koenhoeijmakers** [comment]
If your scope is `scopeStatus` your method call should be `status` with a lower case `s` not an upper case `S`, that might be the solution.
