### ISSUE TITLE
How to make 5 star rating system in laravel ? Video Tutorial Please

### ISSUE THREAD

**Issue by RaisYousaf** [willvincent/laravel-rateable#23]

**Comment by krasidankov** [comment]
Hi. It would be in handy if someone makes an explanation about how it works for those who are learning and don't know much about the framework. Thank you.

**Comment by aminmalekzadeh** [comment]
hi

**Comment by robertnicjoo** [comment]
@krasidankov  @RaisYousaf here you go:  https://tjd-studio.com/blog/how-to-make-laravel-rating-system

**Comment by elemanhillary** [comment]
this should be closed as @robertnicjoo gave a correct answer
