### ISSUE TITLE
How to implement Like and Dislike rating?

### ISSUE THREAD

**Issue by imannms** [willvincent/laravel-rateable#32]
How to implement Like and Dislike rating?
What value should I set?
If I set `like` value to `1` 
and `dislike` value to  `-1`.

Is that the right thing?

**Comment by tuanvu89** [comment]
@imannms consider https://github.com/rtconner/laravel-likeable for that feature

**Comment by willvincent** [comment]
You _could_ do 1 and -1 for like/dislike, but then it would really be more of a "vote up/down" system than like and dislike.
