### ISSUE TITLE
 Column 'rateable_id' cannot be null

### ISSUE THREAD

**Issue by jmbits** [willvincent/laravel-rateable#35]
Newbie here. Sorry if this is not the place to ask for help. 
I am trying to use this library, but I keep getting  Column 'rateable_id' cannot be null.
I have a model for the photos table, which looks pretty much like this:
```
<?php namespace App;

use willvincent\Rateable\Rateable;
use Illuminate\Database\Eloquent\Model;

class Photos extends Model
{
    use Rateable;

}
```
This is how my migration file looks like:

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateRatingsTable extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        Schema::create('ratings', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
            $table->integer('rating');
            $table->morphs('rateable');
            $table->unsignedInteger('user_id')->index();
            $table->index('rateable_id');
            $table->index('rateable_type');
            $table->foreign('user_id')->references('id')->on('users');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down()
    {
        Schema::drop('ratings');
    }
}
```

And this is how my controller looks like:
```
        $builder = Photo::query();

        if (!is_null($photoid)) {
            $builder->where('photoid', '=', $photoid);
        }
        $result = $builder->get();
        $photoid = $result->first();

        $rating =new willvincent\Rateable\Rating;
        $rating->rating = 5;
        $rating->user_id = 1;
        $photo->ratings()->save($rating);
```
I am not using Auth, so the Users table is empty and the default that comes with a fresh laravel project. Any help?
Thanks in advance.

**Comment by marcinsdance** [comment]
I'm having the same issue here.

**Comment by marcinsdance** [comment]
Ok I solved my case. The issue was that I didn't load my model properly and thus it was passing null.
Your case seems to be similar @jmbits - I don't see you initializing the $photo model in your controller.

**Comment by willvincent** [comment]
There must be more to your controller, because what you've included doesn't really make sense to me..

```
        $builder = Photo::query();

        if (!is_null($photoid)) {
            $builder->where('photoid', '=', $photoid);
        }
        $result = $builder->get();
        $photoid = $result->first();

        $rating =new willvincent\Rateable\Rating;
        $rating->rating = 5;
        $rating->user_id = 1;
        $photo->ratings()->save($rating);
```

Or perhaps you've got a typo there..?  It looks as though you are trying conditionally accepting a photo id, and if present loading that model, and then attaching your rating, but the code you've included here doesn't look to actually _do_ that.

Try something like this instead..

```
if ($photoid) {
  $photo = Photo::find($photoid);
  $rating = new willvincent\Rateable\Rating;
  $rating->rating = 5;
  $rating->user_id = 1;
  $photo()->ratings()->save($rating);
}
```

It would appear that you're attempting to attach to a non-existent photo instance, which would explain why you're getting the error you're getting.
