### ISSUE TITLE
Duplicate rating migration file

### ISSUE THREAD

**Issue by sagautam5** [willvincent/laravel-rateable#36]
I have installed this package in my application. Whenever I enter following command

`php artisan rateable:migration`

It creates migration every time with different timestamp value. I think it should check if migration files already exists in the `database/migrations` directory.

**Comment by willvincent** [comment]
Why are you running that multiple times?

**Comment by willvincent** [comment]
This should no longer occur with newest releases.

**Comment by krognome** [comment]
I have installed 2 packages now and both have not considered that people use more then 1 database :'( why can't the whole package inset into 1 db and reference that 1 db even if model uses another? This break the package.

**Comment by willvincent** [comment]
You're welcome to create a pull request, with tests. But complaining about something nobody else has ever asked for isn't very productive.

**Comment by krognome** [comment]
Yeah many aps use multiple DB so I guess this package has not had that much attention or no one said anything and just modified / extended the package. Thanks for the package it saves me a ton of time in development. I need to decide if I should find a rating package that accounts for more then 1 DB or just extend this one.

**Comment by krognome** [comment]
Oh it's because the solution is simple just add protected $connection = 'mysql'; (main db connection name) to: vendor/willvincent/laravel-rateable/src/Rating.php
