### ISSUE TITLE
Get amount of rates

### ISSUE THREAD

**Issue by MukiA** [willvincent/laravel-rateable#41]
I installed the package and realized that there is no support to get the amount of rates for a model. If for example 3 people rate on a post, I would like to see how many people have rated on that post. In this case it would return "3". Is this something that will be added?

**Comment by Mo7sin** [comment]
`Post::first()->ratings->count()`
This will return ratings count for given post.

**Comment by willvincent** [comment]
As @Mo7sin indicated. This package simply provides a polymorphic relationship, so any regular eloquent methods on the relation should work as expected.
