### ISSUE TITLE
averageRating of 5

### ISSUE THREAD

**Issue by robertnicjoo** [willvincent/laravel-rateable#42]
How can i have averageRating of total 5?

like: `4.1` or `3.0` or `2.7` something like that.

so the least is `0` and the most is `5`

**Comment by willvincent** [comment]
Enforce that the only allowed ratings on a given model are a 0, 1, 2, 3, 4 or 5, then use the averageRating() method as indicated in the readme.

**Comment by robertnicjoo** [comment]
thanks for the answer, as this issue was created long ago, currently not remember the function but i remember i solved it in controller by help of `number_format()`.

default `averageRating()` was returning numbers such as 3.458 not round numbers.

thanks anyway.

**Comment by willvincent** [comment]
well yeah, they're the actual averages, if you need to constrain that to a single decimal place you'd need to further number_format it :)
