### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by DubStepMad** [willvincent/laravel-rateable#50]
Any chance on an update for Laravel 8 support soon?

With many packages being updated, personally this is one that is keeping me from updating to Laravel 8.

Thanks 😃

**Comment by rkawajan** [comment]
+1

**Comment by imagina** [comment]
+1

**Comment by DubStepMad** [comment]
For those looking for an alternative which can be easily implemented like this one, I would suggest the following package: https://github.com/multicaret/laravel-acquaintances

**Comment by johnef** [comment]
@willvincent Is it still dose not have support for laravel 8?

**Comment by willvincent** [comment]
Pull requests are appreciated :)

**Comment by Cryborg** [comment]
I am using Laravel 8 (8.24) and it is properly working without any change.

**Comment by willvincent** [comment]
Ah yes, we did incorporate 8.x support a while back.
