### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by erfanhemmati** [willvincent/laravel-rateable#56]
is this package support for laravel 5.8?
when i want to install this package i have some error

  Problem 1
    - Root composer.json requires willvincent/laravel-rateable ^2.3 -> satisfiable by willvincent/laravel-rateable[2.3.0].
    - willvincent/laravel-rateable 2.3.0 requires illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by willvincent** [comment]
The 1.x releases are probably best suited to Laravel 5.8. I haven't used laravel 5.x in a few years, so not sure what else to say here.
