### ISSUE TITLE
fails

### ISSUE THREAD

**Issue by interludic** [willvincent/laravel-rateable#57]
`  SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'bb_ratings_user_id_foreign' are incompatible. (SQL: alter table `bb_ratings` add constraint `bb_ratings_user_id_foreign` foreign key (`user_id`) references `bb_users` (`id`))`

**Comment by interludic** [comment]
Schema::disableForeignKeyConstraints();
        Schema::create('ratings', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('rating');
            $table->morphs('rateable');
            $table->index('rateable_id');
            $table->index('rateable_type');
            $table->integer('user_id')->unsigned();
            $table->foreign('user_id')->references('id')->on('users');
            $table->timestamps();
        });
        Schema::enableForeignKeyConstraints();

Seems to migrate, hopefully no other problems..

**Comment by interludic** [comment]
I need to set the database on the Rating.php model

```protected $connection = 'mysql';```

**Comment by interludic** [comment]
I am using rateOnce

![image](https://user-images.githubusercontent.com/6327261/128675865-498abca7-bcb4-4bbb-a4b5-a83cb11d6fc7.png)

however it seems to be just inserting more every page refresh?
$post = \App\Models\Content\Post::first();
// Add a rating of 3, or change the user's existing rating _to_ 3.
$post->rateOnce(4);
dd(\App\Models\Content\Post::first()->ratings);

**Comment by willvincent** [comment]
It appears that you did not use the migration the package provides, and it is unclear what else you may be doing incorrectly.

If you can provide more useful detail to help guide you back to the right track, or to track down if there is a potential bug feel free to reopen this issue, but otherwise I am going to close it because there's nothing actionable here as it stands currently.
