### ISSUE TITLE
Listing a Model order by average rating

### ISSUE THREAD

**Issue by RezaMrtz** [willvincent/laravel-rateable#58]
How to get a rateable model order by average rating, like a list? I think it can not be handled by eloquent but is there any way to do that?

**Comment by willvincent** [comment]
The most stripped down solution is: 
```
YourModel::withAvg('ratings', 'rating')->orderBy('ratings_avg_rating', 'desc')->take(5)->get();
```

Though any items that aren't rated will have a `null` average rating value and screw up your ordering, so better would be to instead use a custom withCount that coalesces null values to 0, thusly:

```
YourModel::withCount(['ratings as average_rating' => function($query) {
    $query->select(DB::raw('coalesce(avg(rating),0)'));
}])->orderByDesc('average_rating')->take(5)->get();
```

Both examples will grab the first 5, but again if there are unrated items the first will prepend null values before the highest rating, so you'll end up with probably unexpected results.

For performance on a very large dataset, I'd probably store precalculated averages on the model directly, and update that either via cron or when a new rating comes in for that item. 👍
