### ISSUE TITLE
bindShared error

### ISSUE THREAD

**Issue by coycash** [willvincent/laravel-rateable#6]
I get the error 

> Call to undefined method Illuminate\Foundation\Application::bindShared()

when running step with the command
`php artisan rateable:migration`

I am running Laravel 5.2.  Is that the issue?  thanks

**Comment by willvincent** [comment]
My gut reaction is, yeah probably.. 

But, I haven't used laravel 5.2 yet, and haven't really given this or laravel in general any attention lately.

**Comment by willvincent** [comment]
I've found and resolved the problem.

Fixed with commit 8db744c0e3350f4bf030c70db4534573faa5aca7
