### ISSUE TITLE
How to get specific rated data?

### ISSUE THREAD

**Issue by robertnicjoo** [willvincent/laravel-rateable#62]
Hi,

Let say my users have ratings and I went to filter them by rates, let say just get 4 star users. How can I do that with scopes?

`my model`

```PHP
    public function scopeRates($query, $rate = null)
    {
        if(!Empty($rate)){
            return $query->withCount(['ratings as average_rating' => function($q) {
                $q->select(DB::raw('coalesce(avg(rating),0)'));
            }]);
        }
        return $query;
    }
```

`my controller`

```PHP
    $users = usersResource::collection(User::withCount(['ratings as average_rating' => function($query) {
         $query->select(DB::raw('coalesce(avg(rating),0)'));
     }])
     ->rates($request->input('rate') != 'all' ? $request->input('rate') : null)
     ->orderByDesc('average_rating')->take(5)->get());
```

So what query above does by default is to get users and order them by their rates, (5 star to 0 star), and then I have added my scope where it gets user filter `->rates($request->input('rate') != 'all' ? $request->input('rate') : null)` where it gets only users of specific rates (let say user chose 4 stars users only).

> My issue is in model scope and I'm not sure what that query should be in order to filter users by their rates? (in this case just return 4 star users)

**Comment by robertnicjoo** [comment]
@willvincent  any idea?

**Comment by willvincent** [comment]
So, I think your issue is that averages are usually floats, so you'll probably want to round and cast your rating to an integer:

Try this for your scope:
```
    public function scopeRates($query, $rate = null)
    {
        $query->withCount(['ratings as average_rating' => function ($q) {
            $q->select(DB::raw('CAST(round(coalesce(avg(rating),0)) AS INT)'));
        }]);

        if (!empty($rate)) {
            $query->where('average_rating', $rate);
        }

        return $query;
    }
```

This way, `User::rate()->get()` will return all users with their rounded integer rate value, and `User::rate(4)->get()` will grab only users with a rating of 4.

Otherwise, without the rounding and casting to int, average values end up looking like;
- 2.1
- 3.0
- 3.4
etc

**Comment by robertnicjoo** [comment]
@willvincent appreciate your answer, I am getting this error now



> "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INT) from `ratings` where `users`.`id` = `ratings`.`rateable_id` and `ratings`.`' at line 1 (SQL: select `users`.*, (select CAST(round(coalesce(avg(rating),0)) AS INT) from `ratings` where `users`.`id` = `ratings`.`rateable_id` and `ratings`.`rateable_type` = App\\Models\\User) as `average_rating` from `users` where `average_rating` = 4 order by `average_rating` desc limit 5)"

**Comment by willvincent** [comment]
Casting syntax varies slightly by DB.  I was testing with sqlite so I didn't have to stand up a full DB, etc..

Mysql:
```
public function scopeRates($query, $rate = null)
    {
        $query->withCount(['ratings as average_rating' => function ($q) {
            $q->select(DB::raw('CAST(coalesce(avg(rating),0) AS UNSIGNED)'));
        }]);

        if (!empty($rate)) {
            $query->where('average_rating', $rate);
        }

        return $query;
    }
```

Postgres & sqlite:
```
public function scopeRates($query, $rate = null)
    {
        $query->withCount(['ratings as average_rating' => function ($q) {
            $q->select(DB::raw('CAST(coalesce(avg(rating),0) AS INT)'));
        }]);

        if (!empty($rate)) {
            $query->where('average_rating', $rate);
        }

        return $query;
    }
```

**Comment by robertnicjoo** [comment]
@willvincent Thank you.

Testing your first code (MySql - **my database**) will return 

> "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'average_rating' in 'where clause' (SQL: select `users`.*, (select CAST(coalesce(avg(rating),0) AS UNSIGNED) from `ratings` where `users`.`id` = `ratings`.`rateable_id` and `ratings`.`rateable_type` = App\\Models\\User) as `average_rating` from `users` where `average_rating` = 5 order by `average_rating` desc limit 5)"

Using second one (Postgres & sqlite) will return 


> "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INT) from `ratings` where `users`.`id` = `ratings`.`rateable_id` and `ratings`.`' at line 1 (SQL: select `users`.*, (select CAST(coalesce(avg(rating),0) AS INT) from `ratings` where `users`.`id` = `ratings`.`rateable_id` and `ratings`.`rateable_type` = App\\Models\\User) as `average_rating` from `users` where `average_rating` = 4 order by `average_rating` desc limit 5)"

**Comment by willvincent** [comment]
🤷‍♂️

I dunno, it ought to work... what is the query you're actually running?

It ought to look like: `User::rates(4)->get()`

**Comment by robertnicjoo** [comment]
> 🤷‍♂️
> 
> I dunno, it ought to work... what is the query you're actually running?
> 
> It ought to look like: `User::rates(4)->get()`

My scope


```php
public function scopeRates($query, $rate = null)
    {
        $query->withCount(['ratings as average_rating' => function ($q) {
            $q->select(DB::raw('CAST(coalesce(avg(rating),0) AS UNSIGNED)'));
        }]);

        if (!empty($rate)) {
            $query->where('average_rating', $rate);
        }

        return $query;
    }
```

My controller

```php
$users = usersResource::collection(User::verified($request->input('verify') != 'all' ? $request->input('verify') : 'all')
            ->with(['city', 'religion', 'occupation'])
            ->city($city ? $city->id : null)
            ->religion($religion ? $religion->id : null)
            ->occupation($occupation ? $occupation->id : null)
            ->rates($request->input('rate') != 'all' ? $request->input('rate') : null) //<-- here
            ->take(5)->get());
```

> `$request->input('rate')` is equal to numbers between 1 to 5.

**Comment by willvincent** [comment]
It's specifically complaining about the where clause. so it doesn't like referencing average_rating, apparently.. I'm not sure why as it works for me locally, granted I don't have any of that other stuff. It would be nice to see the SQL that is being generated from your query, might help track down where it's failing.

Can you dd() the output, replacing your `get()` with a `toSql()` ?

My simple test
`User::rates(4)->orderBy('average_rating', 'desc')->take(5)->toSql()`

Outputs this:
```
select
  "users".*,
  (select CAST(round(coalesce(avg(rating),0)) AS INT) from "ratings" where "users"."id" = "ratings"."rateable_id" and "ratings"."rateable_type" = ?) as "average_rating"
from "users"
where "average_rating" = ?
order by "average_rating" desc
limit 5
```

(Formatted for clarity)

**Comment by robertnicjoo** [comment]
For me based on your query `User::rates(4)->orderBy('average_rating', 'desc')->take(5)->toSql()` it return

> "select `users`.*, (select CAST(coalesce(avg(rating),0) AS UNSIGNED) from `ratings` where `users`.`id` = `ratings`.`rateable_id` and `ratings`.`rateable_type` = ?) as `average_rating` from `users` where `average_rating` = ? order by `average_rating` desc limit 5"

and based on my query (above) it return this

> message: Call to a member function first() on string

**Comment by willvincent** [comment]
Seems like you've got other issues going on here. I'm sorry I don't think I can really offer much more in the way of assistance here.

I suspect something else in your query is causing problems.

**Comment by robertnicjoo** [comment]
thanks man.
