### ISSUE TITLE
Solution for apps that use separate DB for some models that need to be rateable?

### ISSUE THREAD

**Issue by krognome** [willvincent/laravel-rateable#64]
Hey this is the second package I have installed and this one does not account for multiple DB. Some of my models use a dif DB and the migration does not create rating DB for all of my model DB (there are only 2 DB for my project really). This is a system I have been developing for 12 years and it is very much necessary to have more then 1 DB (old system + new system) in a perfect world if I had a team and it was not just me there would be 1 DB but it's going to take years for me to move everything into this new DB and system. I can write this myself I was just hoping maybe you already have a solution. I am migrating this rating table into other DB now and crossing fingers that it will work.

**Comment by krognome** [comment]
Adding protected $connection = 'mysql'; (main db connection name) to: vendor/willvincent/laravel-rateable/src/Rating.php seems to work well :)

**Comment by willvincent** [comment]
Pull requests are welcome 🙂
