### ISSUE TITLE
While Using this package with livewire components are not re rendering.

### ISSUE THREAD

**Issue by CodeLine6** [willvincent/laravel-rateable#67]
While Using this package with livewire components are not re rendering.

**Comment by willvincent** [comment]
I don't think this is an issue with this package, as all it really does is provide the relationships and some helper functions to get/set ratings/votes.

I'd need to see what you're doing to help you find why it's not updating, but I suspect that the data in your livewire component isn't changing, so there _is_ nothing to re-render, and/or you may need to simply trigger a refresh.

I've got a few places in livewire in an app that i have to manually trigger a refresh, accomplished by:

```
protected $listeners = [
    'refresh' => '$refresh',
];

public function some_method()
{
    // Do stuff here
    
    // Force refresh the component:
    $this->emitSelf('refresh');
}
```
