### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null 

### ISSUE THREAD

**Issue by pratikbarman** [willvincent/laravel-rateable#68]
$music = Music::find(request(('post_id')));
        $rate = request('rate');
        $music->rateOnce($rate, null, request('user_id'));
        $rateAvg = $music->averageRating;

insert into
  `ratings` (
    `rating`,
    `comment`,
    `user_id`,
    `rateable_id`,
    `rateable_type`,
    `updated_at`,
    `created_at`
  )
values
  (
    5,
    ?,
    ?,
    4,
    App \ Models \ Music,
    2023 -08 -04 14: 10: 19,
    2023 -08 -04 14: 10: 19
  )

**Comment by willvincent** [comment]
I imagine you're getting this error because `user_id` is not in your request object.

I'd either switch that to just grab the authenticated user's ID, or specify the auth user id as the default value.

```php
    $music = Music::findOrFail(request.input('post_id'));
    $rate = request.input('rate');
    $music->rateOnce($rate, null, request.input('user_id', Auth::user()->id));
    $rateAvg = $music->averageRating;
```

In any case, this isn't really an issue with this package ;)
