### ISSUE TITLE
Problems implementing in my controller

### ISSUE THREAD

**Issue by catoruno** [willvincent/laravel-rateable#8]
I tried implemented the rating on muy controller, but I had this issue.

Class 'App\Http\Controllers\willvincent\Rateable\Rating' not found

This is my controller.
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Dish;

class RatingController extends Controller
{
    //

    public function rating($dish_id,$stars){
    	$dish = Dish::find($dish_id);
    	$rating = new willvincent\Rateable\Rating;
		$rating->rating = $stars;
		$rating->user_id = \Auth::id();

		$dish->ratings()->save($rating);

		return redirect()->to($this->getRedirectUrl());
    }
}

I need some help.

**Comment by ynsp** [comment]
catoruno add on the top of your controller 
`use willvincent\Rateable\Rating; `

and then create a new Rating object
`$rating = new Rating;`

**Comment by willvincent** [comment]
or change your `$rating = new willvincent\Rateable\Rating;` line to: `$rating = new \willvincent\Rateable\Rating;`

(note the leading backslash).

Specifically the problem you are having is that it's looking for the class within your current App\Http\Controllers namespace.

**Comment by makerstorage** [comment]
Please update the read me according to below explanation
or change your $rating = new willvincent\Rateable\Rating; line to: $rating = new \willvincent\Rateable\Rating;

**Comment by willvincent** [comment]
Really doesn't seem necessary since one really ought to import the class in the first place
